/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AmazonGiftCardCode = string;
export interface BuyerContactDetails { 'email' : [] | [string] }
export type ClientAddress = string;
export type EthereumWalletAddress = string;
export type NexusBankId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'productTitle' : string,
  'createdAt' : Timestamp,
  'productId' : ProductId,
  'buyer' : Principal,
  'productPrice' : bigint,
}
export type OrderId = bigint;
export type OrderStatus = { 'pending' : null } |
  { 'accepted' : Timestamp } |
  { 'declined' : null };
export type PayPalEmail = string;
export type PaymentMethod = { 'amazon_gift_card' : AmazonGiftCardCode } |
  { 'ethereum' : EthereumWalletAddress } |
  { 'nexus_bank' : NexusBankId } |
  { 'paypal' : PayPalEmail } |
  { 'bitcoin' : ClientAddress };
export interface Product {
  'id' : ProductId,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'price' : bigint,
  'accountDetails' : string,
}
export type ProductId = bigint;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOrder' : ActorMethod<[OrderId], undefined>,
  'addProduct' : ActorMethod<[string, string, bigint, string], ProductId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineOrder' : ActorMethod<[OrderId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'editProduct' : ActorMethod<
    [ProductId, string, string, bigint, string],
    undefined
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBuyerContactDetails' : ActorMethod<[Principal], BuyerContactDetails>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getOrderAccountDetails' : ActorMethod<[OrderId], string>,
  'getOrderBuyerContact' : ActorMethod<[OrderId], BuyerContactDetails>,
  'getOrdersByBuyer' : ActorMethod<[Principal], Array<Order>>,
  'getPaymentInstructions' : ActorMethod<[string], string>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[ProductId, PaymentMethod], OrderId>,
  'registerStaff' : ActorMethod<[string], undefined>,
  'saveBuyerContactDetails' : ActorMethod<[[] | [string]], undefined>,
  'setPaymentInstructions' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];